### PR TITLE
Release v5.5.0

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by qrkourier** [comment]
@dariuszSki I'm getting close to ready to release and it would be great if you could test drive the `nfctl` CLI that's installed with this version.

**Comment by qrkourier** [comment]
> @dariuszSki I'm getting close to ready to release and it would be great if you could test drive the `nfctl` CLI that's installed with this version.

You could install from the tarball in https://github.com/netfoundry/python-netfoundry/actions/runs/1900226006 or the lastest TestPyPi in https://test.pypi.org/project/netfoundry/

**Comment by dariuszSki** [comment]
ok, let me try

**Comment by dariuszSki** [comment]
IN windows this doe snot seem to work as expected to provide the credentials if my understanding is correct.
nfctl --credentials C:\Users\dsliw\.netfoundry\credentials-cldeng.json
```
PS C:\Users\dsliw> nfctl login organization
⚠ token renewal is disabled without API account credentials
☒ credentials needed to renew expired or imminently-expiring token
PS C:\Users\dsliw> nfctl --credentials C:\Users\dsliw\.netfoundry\credentials-cldeng.json
ℹ using credentials in C:\Users\dsliw\.netfoundry\credentials-cldeng.json
⚠ renewing expired or imminently-expiring token
ℹ using credentials in C:\Users\dsliw\.netfoundry\credentials-cldeng.json
⚠ renewing expired or imminently-expiring token
caller:
    active: true
    auth0ClientId: null
    authenticationUrl: https://netfoundry-production-xfjiye.auth.us-east-1.amazoncognito.com/oauth2/token
    awsCognitoClientId: us-east-1_3uDA8bXTz|4s3kisq9hqag5vd7gdqkh2q02j
    contactEmail: dariusz.sliwinski@netfoundry.io
    createdAt:
        epochSecond: 1627596019
        nano: 0
    deletedAt: null
    description: ''
    email: dariusz.sliwinski@netfoundry.io
    environment: production
    id: 266cca2a-edca-4b05-8270-5f89eb5ba0e5
    label: cldeng
    name: dariuszSliwinskiKey2
    organizationId: 95068bb0-864b-4930-b06e-9acf4957c826
    tenantId: 95068bb0-864b-4930-b06e-9acf4957c826
    type: ApiAccountIdentity
    updatedAt: null
organization:
    active: true
    createdAt:
        epochSecond: 1583359454
        nano: 0
    deleted: false
    deletedAt: null
    id: 95068bb0-864b-4930-b06e-9acf4957c826
    identityProviders:
    -   active: true
        auth0ConnectionId: Username-Password-Authentication
        auth0ConnectionType: Database
        createdAt:
            epochSecond: 1583359454
            nano: 0
        deletedAt: null
        id: 05ca2d73-6d74-4d14-9594-527a61690164
        name: cldeng Simple Username/Password
        organizationId: 95068bb0-864b-4930-b06e-9acf4957c826
        updatedAt: null
    label: cldeng
    mfaProvider: None
    name: cldeng
    updatedAt:
        epochSecond: 1624283491
        nano: 0

PS C:\Users\dsliw> nfctl login organization
⚠ token renewal is disabled without API account credentials
☒ credentials needed to renew expired or imminently-expiring token
PS C:\Users\dsliw>
```

**Comment by dariuszSki** [comment]
when I use the env variable that works.
```
PS C:\Users\dsliw> $env:NETFOUNDRY_API_ACCOUNT = "C:\Users\dsliw\.netfoundry\credentials-cldeng.json"
PS C:\Users\dsliw> nfctl login organization
ℹ using credentials in C:\Users\dsliw\.netfoundry\credentials-cldeng.json
⚠ renewing expired or imminently-expiring token

# source this output like
# $ source <(nfctl --credentials credentials.json login organization)
export NETFOUNDRY_API_TOKEN="***"
# or, alternatively, silently-paste and export to child procs
# $ read -s NETFOUNDRY_API_TOKEN && export NETFOUNDRY_API_TOKEN
# then logout of organization with
# $ unset NETFOUNDRY_API_TOKEN

PS C:\Users\dsliw>
```

**Comment by dariuszSki** [comment]
In linux, I get error that I need to provide "--network" option when running  command to list edge-routers, even though I provided one 
```
dsliwinski@DariuszDesktop:/mnt/c/Users/dsliw$ nfctl login organization
ℹ using credentials in /home/dsliwinski/.netfoundry/credentials-cldeng.json
⚠ renewing expired or imminently-expiring token

# source this output like
# $ source <(nfctl --credentials credentials.json login organization)
export NETFOUNDRY_API_TOKEN="***"
# or, alternatively, silently-paste and export to child procs
# $ read -s NETFOUNDRY_API_TOKEN && export NETFOUNDRY_API_TOKEN
# then logout of organization with
# $ unset NETFOUNDRY_API_TOKEN

dsliwinski@DariuszDesktop:/mnt/c/Users/dsliw$ nfctl --network PRIVATEDCMGMT list edge-routers
ℹ using credentials in /home/dsliwinski/.netfoundry/credentials-cldeng.json
⚠ renewing expired or imminently-expiring token
☒ need --network to configure a network
dsliwinski@DariuszDesktop:/mnt/c/Users/dsliw$
```

**Comment by qrkourier** [comment]
> IN windows this does not seem to work as expected to provide the credentials if my understanding is correct. nfctl --credentials C:\Users\dsliw.netfoundry\credentials-cldeng.json
> 

@dariuszSki I have changed `login organization` to work this way. Now the login token is persisted in your homedir cache according to XDG spec and only renewed with configured creds if needed.

**Pull request merged**
