### PR TITLE
deprecate data_center_id for creating hosted routers 

### PR DESCRIPTION
**Pull request by qrkourier**
in favor of provider, location_code

### CODE REVIEW

**Review by dariuszSki — APPROVED** [review]

**Comment by qrkourier** [comment]
@dariuszSki I'm thinking about how to improve CI for releases before we merge this, since it's not urgent. Two main ideas to think about:
1. running some packets through the demo network
2. running the latest release of the Ansible collection with the new version of the module

**Comment by dariuszSki** [comment]
I can test it with my ansible script now

**Comment by dariuszSki** [comment]
but you built the test on 5.2.12 and .13 is latest. I guess it i sok. I downgraded my to your test version

**Comment by qrkourier** [comment]
> but you built the test on 5.2.12 and .13 is latest. I guess it is ok. I downgraded mine to your test version

@dariuszSki Correct, Versioneer will compute the version from the Git checkout and so the pre-release versions will be like 5.2.12-devN... until the 5.2.13 tag is created by `git flow release finish`.

**Comment by dariuszSki** [comment]
@qrkourier Also Are you going to push the changes to ansible for the edge router? Wanted to test it.

**Comment by qrkourier** [comment]
> @qrkourier Also Are you going to push the changes to ansible for the edge router? Wanted to test it.

I plan to release PyPi 5.3.0 after performing a local test with latest Ansible (like your local test), and then I'll start adapting the collection to deprecate data_center_id in netfoundry/ansible-collection repo.

**Pull request merged**
